### ISSUE TITLE
Serializer example is wrong, it should be new JsonSerializer()

### ISSUE THREAD

**Issue by tolgaulas** [xobotyi/beansclient#15]
Examples of beansclient\Serializer has the below reference:
```
use xobotyi\beansclient\Serializer\Json;
$client = new BeansClient(new Connection(), new Json());
```
which is wrong since the class name is JsonSerializer, the correct one should be.
```
use xobotyi\beansclient\Serializer\JsonSerializer;
$client = new BeansClient(new Connection(), new JsonSerializer());
```

**Comment by xobotyi** [comment]
Sadly has absolutely no time to update the docs - this is why lib in alpha stage.

**Comment by mmcgrathRSD** [comment]
Will you accept a PR to fix this issue?
