### ISSUE TITLE
Echo на клиенте

### ISSUE THREAD

**Issue by chasovoy85** [xobotyi/beansclient#23]
Как получить что то в echo на клиенте до того как завершит работу воркер?
Клиент
`$job = $beansClient->useTube('myAwesomeTube')
    ->put($data);
echo "ok";`
Воркер
`$job = $beansClient->watchTube('myAwesomeTube')
    ->reserve();
if ($job) {
	$data1 = unserialize($job->payload);
       $job->release(BeansClient::DEFAULT_PRIORITY, 600);`

echo "ok"; я получаю только через 10 минут, а как можно получить сразу?

**Comment by xobotyi** [comment]
В старом клиенте `->reserve(0)`
В новом клиенте, который v3 - использовать `->reserveWithTimeout(0)`
