### ISSUE TITLE
Is there a peek-buried command?

### ISSUE THREAD

**Issue by coenier** [xobotyi/beansclient#24]
Hi

Is there peek-buried command in the library to query the buried jobs? 

I looked at the BeansClient class and I can only see a Peak method but it expects job id.

I am using the version 2 code.

**Comment by xobotyi** [comment]
This command wasnt in the protocol v1.10.
I'll do refactoring soon and upgrade to protocol v1.12

**Comment by coenier** [comment]
Great stuff, thanx

**Comment by xobotyi** [comment]
Implemented in v3
