### ISSUE TITLE
Got unexpected status code [DEADLINE_SOON]

### ISSUE THREAD

**Issue by Punkley** [xobotyi/beansclient#5]
Bug causing a fatal error

> PHP Fatal error:  Uncaught xobotyi\beansclient\Exception\Command: Got unexpected status code [DEADLINE_SOON] in /data/beta/websocket/vendor/xobotyi/beansclient/src/Command/Reserve.php:65
>Stack trace:
>#0 /data/beta/websocket/vendor/xobotyi/beansclient/src/BeansClient.php(122): xobotyi\beansclient\Command\Reserve->parseResponse(Array, NULL)
>#1 /data/beta/websocket/vendor/xobotyi/beansclient/src/BeansClient.php(304): xobotyi\beansclient\BeansClient->dispatchCommand(Object(xobotyi\beansclient\Command\Reserve))
>#2 /data/beta/websocket/bin/wsbs-worker.php(30): xobotyi\beansclient\BeansClient->reserve(30)
>#3 /data/beta/websocket/bin/wsbs-worker.php(261): BeanstalkdWorker->run()
>#4 {main

It should understand "[DEADLINE_SOON]" which is in beanstalkd 1.10

- [ ] Issue isn't fixed in `dev` branch

**Comment by xobotyi** [comment]
ATM working on new package version, where it'll be fixed
